import { PrismaClient, WelfareCategory, WelfareSource } from '@prisma/client'

const prisma = new PrismaClient()

const programs = [
  // ── 생활비·자립수당 ──────────────────────────────────────
  {
    name: '자립수당',
    description: '보호종료아동이 안정적으로 자립할 수 있도록 매월 지급하는 생활 지원금',
    category: WelfareCategory.LIVING_EXPENSE,
    source: WelfareSource.BOKJIRO,
    operator: '보건복지부 / 지자체',
    applyUrl: 'https://www.bokjiro.go.kr',
    infoUrl: 'https://www.bokjiro.go.kr',
    benefitAmount: '월 40만 원 (2024년 기준, 지자체 추가 지원 포함 시 상이)',
    benefitMonthly: 40,
    benefitDuration: '최대 60개월',
    eligibility: {
      minAge: 18,
      maxAge: 24,
      protectionEndedWithin: 60,
      conditions: [
        '아동복지시설·가정위탁·공동생활가정 보호종료 후 5년 이내',
        '시설 퇴소 또는 가정위탁 해제된 만 18세 이상',
        '기초생활수급자 또는 차상위계층이 아닐 것 (일부 예외 있음)',
      ],
      excludeIfReceiving: [],
    },
    requiredDocs: ['주민등록등본', '보호종료확인서', '통장사본', '신분증 사본'],
    isYearRound: true,
    regionRestrict: [],
    tags: ['자립수당', '생활비', '월정액', '보호종료'],
    isPostJarip: false,
  },
  {
    name: '자립정착금',
    description: '보호종료 시점에 일시 지급되는 초기 자립 지원금 (지자체별 금액 상이)',
    category: WelfareCategory.LIVING_EXPENSE,
    source: WelfareSource.JARIPJUNGBO,
    operator: '지자체',
    applyUrl: 'https://www.jaripjungbo.or.kr',
    benefitAmount: '500만 원 ~ 2,000만 원 (지자체별 상이)',
    benefitLumpsum: 1000,
    benefitDuration: '일시금',
    eligibility: {
      conditions: [
        '보호종료 후 1개월 이내 신청 원칙 (지자체마다 다름)',
        '아동복지시설·가정위탁·공동생활가정 퇴소자',
      ],
      excludeIfReceiving: [],
    },
    requiredDocs: ['보호종료확인서', '주민등록등본', '통장사본'],
    isYearRound: true,
    regionRestrict: [],
    tags: ['자립정착금', '일시금', '보호종료'],
    isPostJarip: false,
  },
  {
    name: '긴급복지지원 (생계지원)',
    description: '갑작스러운 위기 상황으로 생계유지가 어려울 때 일시적으로 생계비를 지원',
    category: WelfareCategory.EMERGENCY,
    source: WelfareSource.BOKJIRO,
    operator: '보건복지부 / 지자체',
    applyUrl: 'https://www.bokjiro.go.kr/ssis-tbu/twataa/wlfareInfo/moveTWAT52011M.do',
    benefitAmount: '1인 가구 월 713,100원 (2024년 기준)',
    benefitMonthly: 71,
    benefitDuration: '최대 6개월',
    eligibility: {
      conditions: [
        '갑작스러운 위기사유 발생 (실직, 질병, 재난 등)',
        '소득이 기준 중위소득 75% 이하',
        '재산 기준 충족',
        '자립수당 종결 이후 신청 가능 확대',
      ],
      excludeIfReceiving: [],
    },
    requiredDocs: ['신분증', '위기사유 증빙서류', '소득·재산 관련 서류'],
    isYearRound: true,
    regionRestrict: [],
    tags: ['긴급복지', '생계지원', '위기', '자립수당종결후'],
    isPostJarip: true,
  },
  {
    name: '기초생활수급 (생계급여)',
    description: '소득인정액이 기준 이하인 경우 생계비를 매월 지원하는 공공부조',
    category: WelfareCategory.BASIC_LIVELIHOOD,
    source: WelfareSource.BOKJIRO,
    operator: '보건복지부',
    applyUrl: 'https://www.bokjiro.go.kr',
    benefitAmount: '기준 중위소득 32% 이하 시 차액 지급 (1인 가구 월 약 713,102원)',
    benefitMonthly: 71,
    benefitDuration: '자격 유지 기간',
    eligibility: {
      conditions: [
        '소득인정액이 기준 중위소득 32% 이하 (생계급여 기준)',
        '부양의무자 기준 완화 적용',
        '자립수당 종결 후 소득이 낮은 경우 전환 가능',
      ],
      excludeIfReceiving: ['자립수당 수급 중에는 소득 인정 여부 확인 필요'],
    },
    requiredDocs: ['신분증', '주민등록등본', '소득·재산 신고서', '금융정보 제공 동의서'],
    isYearRound: true,
    regionRestrict: [],
    tags: ['기초생활', '생계급여', '자립수당종결후', '저소득'],
    isPostJarip: true,
  },
  {
    name: '청년내일저축계좌',
    description: '저소득 청년이 매월 10만 원 저축 시 정부가 매칭 적립 (최대 월 30만 원)',
    category: WelfareCategory.ASSET_BUILDING,
    source: WelfareSource.BOKJIRO,
    operator: '보건복지부',
    applyUrl: 'https://www.bokjiro.go.kr',
    benefitAmount: '3년 만기 시 최대 1,440만 원 (본인 360만 원 + 정부 1,080만 원)',
    benefitDuration: '3년',
    eligibility: {
      minAge: 19,
      maxAge: 34,
      conditions: [
        '기준 중위소득 100% 이하 가구',
        '현재 근로·사업소득 있는 자',
        '연 소득 2,400만 원 이하',
        '자립준비청년은 소득 기준 우대 적용',
      ],
      excludeIfReceiving: [],
    },
    requiredDocs: ['신분증', '소득 증빙서류', '통장사본', '재직증명서 또는 사업자등록증'],
    applyStartDate: new Date('2024-07-01'),
    applyEndDate: new Date('2024-08-16'),
    isYearRound: false,
    regionRestrict: [],
    tags: ['자산형성', '저축', '청년내일저축계좌', '매칭'],
    isPostJarip: false,
  },

  // ── 주거 ─────────────────────────────────────────────────
  {
    name: 'LH 전세임대주택 (자립준비청년)',
    description: '자립준비청년이 원하는 주택을 직접 구하면 LH가 임대계약을 맺고 저렴하게 재임대',
    category: WelfareCategory.HOUSING,
    source: WelfareSource.LH,
    operator: '한국토지주택공사(LH)',
    applyUrl: 'https://apply.lh.or.kr',
    infoUrl: 'https://apply.lh.or.kr',
    benefitAmount: '수도권 최대 1억 3,500만 원, 광역시 1억 원, 기타 8,500만 원 한도 내 전세금 지원 / 월 임대료 전세금의 1~2%',
    benefitDuration: '최초 2년, 최장 20년 거주 가능',
    eligibility: {
      minAge: 18,
      maxAge: 35,
      conditions: [
        '보호종료 후 5년 이내 (만 18세 이상 ~ 만 35세 이하)',
        '무주택자',
        '자산 기준 충족',
      ],
      excludeIfReceiving: [],
    },
    requiredDocs: ['보호종료확인서', '주민등록등본', '신분증', '무주택 확약서'],
    isYearRound: true,
    regionRestrict: [],
    tags: ['주거', 'LH', '전세임대', '청년'],
    isPostJarip: false,
  },
  {
    name: '자립준비청년 주거비 지원사업 (희망플러스)',
    description: '서울시 자립준비청년 대상 월세 보조 지원사업',
    category: WelfareCategory.HOUSING,
    source: WelfareSource.LOCAL_GOV,
    operator: '서울시',
    applyUrl: 'https://youth.seoul.go.kr',
    benefitAmount: '월 20만 원 이내 (최대 12개월)',
    benefitMonthly: 20,
    benefitDuration: '12개월',
    eligibility: {
      minAge: 18,
      maxAge: 24,
      conditions: [
        '서울시 거주 자립준비청년',
        '보호종료 후 5년 이내',
        '월세 거주자',
        '소득 기준 중위소득 100% 이하',
      ],
      excludeIfReceiving: [],
    },
    requiredDocs: ['보호종료확인서', '주민등록등본', '임대차계약서', '통장사본'],
    isYearRound: false,
    regionRestrict: ['서울'],
    tags: ['주거비', '월세', '서울', '희망플러스'],
    isPostJarip: false,
  },

  // ── 장학금·등록금 ────────────────────────────────────────
  {
    name: '국가장학금 I유형 (자립준비청년 우선지원)',
    description: '자립준비청년은 소득분위 무관하게 등록금 전액 지원 우선 적용',
    category: WelfareCategory.SCHOLARSHIP,
    source: WelfareSource.KEDI,
    operator: '한국장학재단',
    applyUrl: 'https://www.kosaf.go.kr',
    infoUrl: 'https://www.kosaf.go.kr',
    benefitAmount: '등록금 전액 (최대 연간 700만 원)',
    benefitDuration: '재학 기간',
    eligibility: {
      conditions: [
        '국내 대학 재학(또는 입학 예정)자',
        '보호종료아동(아동복지법에 의한 보호 종료)',
        '청소년쉼터 퇴소 청년도 별도 지원 대상 확인 가능',
        '소득분위 제한 없음',
      ],
      excludeIfReceiving: [],
    },
    requiredDocs: ['보호종료확인서', '재학증명서', '주민등록등본'],
    applyStartDate: new Date('2025-02-01'),
    applyEndDate: new Date('2025-02-21'),
    isYearRound: false,
    regionRestrict: [],
    tags: ['장학금', '등록금', '국가장학금', '대학', '우선지원'],
    isPostJarip: false,
  },
  {
    name: '초록우산어린이재단 자립지원 장학금',
    description: '초록우산어린이재단이 자립준비청년에게 지원하는 생활·학업 장학금',
    category: WelfareCategory.SCHOLARSHIP,
    source: WelfareSource.GREEN_UMBRELLA,
    operator: '초록우산어린이재단',
    applyUrl: 'https://www.childfund.or.kr',
    benefitAmount: '연간 최대 200~400만 원 (장학 유형별 상이)',
    benefitDuration: '연간',
    eligibility: {
      minAge: 18,
      maxAge: 24,
      conditions: [
        '자립준비청년 (보호종료아동)',
        '대학 재학 또는 직업훈련 참여자',
        '소득 기준 충족',
      ],
      excludeIfReceiving: [],
    },
    requiredDocs: ['보호종료확인서', '재학·훈련 증빙서류', '소득 증빙서류', '통장사본'],
    isYearRound: false,
    regionRestrict: [],
    tags: ['장학금', '초록우산', '민간', '생활비'],
    isPostJarip: false,
  },
  {
    name: '아동권리보장원 자립지원 장학금',
    description: '아동권리보장원 연계 자립준비청년 대상 학업 지원 장학금',
    category: WelfareCategory.SCHOLARSHIP,
    source: WelfareSource.CHILD_RIGHTS,
    operator: '아동권리보장원',
    applyUrl: 'https://www.ncrc.or.kr',
    benefitAmount: '연간 50만 ~ 200만 원 (유형별 상이)',
    benefitDuration: '연간',
    eligibility: {
      conditions: [
        '보호종료아동',
        '대학교 재학생',
        '소득 기준 충족',
      ],
      excludeIfReceiving: [],
    },
    requiredDocs: ['보호종료확인서', '재학증명서', '성적증명서', '통장사본'],
    isYearRound: false,
    regionRestrict: [],
    tags: ['장학금', '아동권리보장원', '학업'],
    isPostJarip: false,
  },

  // ── 취업·직업훈련 ────────────────────────────────────────
  {
    name: '자립준비청년 일경험 프로그램',
    description: '자립준비청년이 다양한 직장을 단기 체험하고 진로를 탐색할 수 있도록 지원',
    category: WelfareCategory.EMPLOYMENT,
    source: WelfareSource.WORK24,
    operator: '고용노동부 / 고용24',
    applyUrl: 'https://www.work24.go.kr',
    benefitAmount: '참여 수당 별도 지급 (월 최소 최저임금 이상)',
    benefitDuration: '1~6개월 (프로그램별 상이)',
    eligibility: {
      minAge: 18,
      maxAge: 34,
      conditions: [
        '자립준비청년',
        '미취업 상태',
        '고용보험 가입 이력 없거나 단기인 경우',
      ],
      excludeIfReceiving: [],
    },
    requiredDocs: ['신분증', '보호종료확인서', '주민등록등본'],
    isYearRound: true,
    regionRestrict: [],
    tags: ['일경험', '취업', '직업훈련', '고용24'],
    isPostJarip: false,
  },
  {
    name: '국민취업지원제도 I유형',
    description: '취업 의욕이 있는 저소득층 구직자에게 구직활동비와 취업 지원 서비스 제공',
    category: WelfareCategory.EMPLOYMENT,
    source: WelfareSource.WORK24,
    operator: '고용노동부',
    applyUrl: 'https://www.kua.go.kr',
    benefitAmount: '구직촉진수당 월 50만 원 × 6개월 + 취업 성공 시 취업성공수당 최대 150만 원',
    benefitMonthly: 50,
    benefitDuration: '최대 6개월',
    eligibility: {
      minAge: 15,
      maxAge: 69,
      conditions: [
        '기준 중위소득 60% 이하 가구',
        '최근 2년 이내 100일 이상 취업 경험 없음',
        '구직 의사 및 활동 능력 있는 자',
        '자립준비청년은 소득 요건 완화 적용',
      ],
      excludeIfReceiving: [],
    },
    requiredDocs: ['신분증', '주민등록등본', '소득·재산 확인서류'],
    isYearRound: true,
    regionRestrict: [],
    tags: ['국민취업지원', '구직촉진수당', '취업지원'],
    isPostJarip: false,
  },
  {
    name: '청년도약계좌',
    description: '청년이 매월 70만 원 한도 내 자유적립 시 정부가 기여금 지원 (소득별 차등)',
    category: WelfareCategory.ASSET_BUILDING,
    source: WelfareSource.ONTONGYOUTH,
    operator: '금융위원회',
    applyUrl: 'https://ylaccount.kinfa.or.kr',
    benefitAmount: '5년 만기 최대 5,000만 원 (정부 기여금 + 이자)',
    benefitDuration: '5년',
    eligibility: {
      minAge: 19,
      maxAge: 34,
      conditions: [
        '개인 소득 7,500만 원 이하',
        '가구 소득 기준 중위소득 250% 이하',
        '직전 3개년 중 1회 이상 금융소득종합과세 대상 아닌 자',
        '자립준비청년은 소득 요건 완화 적용',
      ],
      excludeIfReceiving: [],
    },
    requiredDocs: ['신분증', '소득 증빙서류'],
    applyStartDate: new Date('2025-06-01'),
    isYearRound: false,
    regionRestrict: [],
    tags: ['청년도약계좌', '자산형성', '저축'],
    isPostJarip: false,
  },

  // ── 의료·건강 ────────────────────────────────────────────
  {
    name: '자립준비청년 의료비 지원',
    description: '보호종료 후 의료급여 자격 상실에 따른 의료비 부담을 지원하는 사업',
    category: WelfareCategory.MEDICAL,
    source: WelfareSource.BOKJIRO,
    operator: '보건복지부 / 지자체',
    applyUrl: 'https://www.bokjiro.go.kr',
    benefitAmount: '입원 최대 100만 원, 외래 최대 30만 원 (연간)',
    benefitDuration: '연간',
    eligibility: {
      minAge: 18,
      maxAge: 24,
      conditions: [
        '보호종료 후 5년 이내',
        '의료급여 자격 없는 자',
        '소득·재산 기준 충족',
      ],
      excludeIfReceiving: [],
    },
    requiredDocs: ['보호종료확인서', '주민등록등본', '진료비 영수증', '통장사본'],
    isYearRound: true,
    regionRestrict: [],
    tags: ['의료비', '건강', '의료급여'],
    isPostJarip: false,
  },

  // ── 경기도 지역 특화 ─────────────────────────────────────
  {
    name: '경기도 청년 기본소득',
    description: '경기도 거주 만 24세 청년에게 지역화폐로 분기별 25만 원 지급',
    category: WelfareCategory.LIVING_EXPENSE,
    source: WelfareSource.LOCAL_GOV,
    operator: '경기도',
    applyUrl: 'https://www.gyeonggi.go.kr',
    benefitAmount: '분기별 25만 원 × 4회 = 연간 100만 원 (지역화폐)',
    benefitMonthly: 8,
    benefitDuration: '1년',
    eligibility: {
      minAge: 24,
      maxAge: 24,
      conditions: [
        '경기도 거주 만 24세 청년',
        '경기도 내 3년 이상 거주 또는 최근 1년 이상 거주',
      ],
      excludeIfReceiving: [],
    },
    requiredDocs: ['신분증', '주민등록등본'],
    isYearRound: false,
    regionRestrict: ['경기'],
    tags: ['경기도', '청년기본소득', '지역화폐'],
    isPostJarip: false,
  },
  {
    name: '서울시 청년수당',
    description: '서울 거주 미취업 청년에게 월 50만 원씩 최대 6개월 활동 지원',
    category: WelfareCategory.LIVING_EXPENSE,
    source: WelfareSource.LOCAL_GOV,
    operator: '서울시',
    applyUrl: 'https://youth.seoul.go.kr',
    benefitAmount: '월 50만 원 × 최대 6개월',
    benefitMonthly: 50,
    benefitDuration: '최대 6개월',
    eligibility: {
      minAge: 19,
      maxAge: 34,
      conditions: [
        '서울 거주 미취업 청년',
        '소득 기준 중위소득 150% 이하',
        '고용보험 미가입 또는 단기 가입',
      ],
      excludeIfReceiving: [],
    },
    requiredDocs: ['신분증', '주민등록등본', '미취업 증빙서류'],
    isYearRound: false,
    regionRestrict: ['서울'],
    tags: ['서울', '청년수당', '활동지원금'],
    isPostJarip: false,
  },
]

async function main() {
  console.log('🌱 복지 프로그램 데이터 시딩 시작...')

  for (const program of programs) {
    await prisma.welfareProgram.upsert({
      where: { id: program.name },
      update: program,
      create: { ...program, id: program.name.replace(/\s/g, '_') },
    })
  }

  console.log(`✅ ${programs.length}개 복지 프로그램 시딩 완료`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
